easy_admin:
    list:
        max_results: 10
        actions:
#            - { name: 'show', icon: 'search' ,label: 'Montrer'}
            - { name: 'edit', icon: 'pencil' ,label: 'Edition' }
            - { name: 'delete', icon: 'remove' ,label: 'Suppression'}
    formats:
        time:     'H:i'
        number: '%.2f €'

    entities:
        Product:
            class: App\Entity\Product
            label: 'Les Produits'
            form:
                title: 'Ajouter un nouveau produit'
                fields:
                    - { property: 'title',label: 'Nom du produit',css_class: 'text-center',type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Product' }}
                    - {property: 'image', value: 'Delicefrite/null.jpg' }

            list:
                title: "Produits"
                max_results: 10
                fields:
                    - { property: 'title',label: 'Nom du produit',css_class: 'text-center'}
                    - { property: 'menus',label: 'Nbr de produit dans les menus',css_class: 'text-center'}
                    - image
            search:
                fields:
                    - { property: 'title',label: 'Nom du produit',css_class: 'text-center'}
                    - { property: 'menus',label: 'Nbr de produit dans les menus',css_class: 'text-center'}
                    - image

        Menus:
            class: App\Entity\Menu
            label: 'Les Menus'
            form:
                help: 'Attention les champs TVA , Produits et Catégorie doivent être renseigner avant de créer un nouveau menu'
                title: 'Ajouter un nouveau menu'
                fields:
                    - { property: 'name',label: 'Nom du menu',css_class: 'text-center'}
                    - { property: 'price',label: 'Prix',css_class: 'text-center', help: 'Le prix doit être HT'}
                    - { type: 'divider' }
                    - { property: 'tva',label: 'Tva',css_class: 'text-center', actions: ['new']}
                    - { property: 'category',label: 'Catégorie',css_class: 'text-center'}
                    - { property: 'products',label: 'Produit(s)',css_class: 'text-center'}

            list:
                title: "Menus"
                max_results: 10

                fields:
                    - { property: 'name',label: 'Nom du menu',css_class: 'text-center'}
                    - { property: 'price',label: 'Prix',css_class: 'text-center'}
                    - { property: 'tva',label: 'Tva',css_class: 'text-center'}
                    - { property: 'category',label: 'Catégorie',css_class: 'text-center'}
                    - { property: 'products',label: 'Nombre de produit',css_class: 'text-center'}

            search:
                fields:
                    - { property: 'name',label: 'Nom du menu',css_class: 'text-center'}
                    - { property: 'price',label: 'Prix',css_class: 'text-center'}
                    - { property: 'tva',label: 'Tva',css_class: 'text-center'}
                    - { property: 'category',label: 'Catégorie',css_class: 'text-center'}


        Category:
            class: App\Entity\Category
            label: 'Les Catégories'
            form:
                title: 'Ajouter une nouvelle catégorie'
                fields:
                    - { property: 'nameCat',label: 'Nom du la catégorie',css_class: 'text-center'}
            list:
                title: "Catégorie"
                max_results: 10
                fields:
                    - { property: 'nameCat',label: 'Nom du la catégorie',css_class: 'text-center'}
                    - { property: 'menus',label: 'Nombre de menu',css_class: 'text-center'}

            search:
                fields:
                    - { property: 'nameCat',label: 'Nom du la catégorie',css_class: 'text-center'}


        Horaire:
            class: App\Entity\Horaire
            label: 'Les Horaires'
            disabled_actions: ['new','delete','search']
            list:
                title: "Horaires"
                max_results: 10
                fields:
                    - { property: 'id',label: 'Ordre',css_class: 'text-center'}
                    - { property: 'jour',label: 'jour',css_class: 'text-center'}
                    - { property: 'midiDebut',label: 'Ouverture du midi',css_class: 'text-center'}
                    - { property: 'midifin',label: 'Fermeture du midi',css_class: 'text-center'}
                    - { property: 'soirdebut',label: 'Ouverture du soir',css_class: 'text-center'}
                    - { property: 'soirfin',label: 'Fermeture du soir',css_class: 'text-center'}

            search:
                fields:
                    - { property: 'jour',label: 'jour',css_class: 'text-center'}
                    - { property: 'midiDebut',label: 'Ouverture du midi',css_class: 'text-center'}
                    - { property: 'midifin',label: 'Fermeture du midi',css_class: 'text-center'}
                    - { property: 'soirdebut',label: 'Ouverture du soir',css_class: 'text-center'}
                    - { property: 'soirfin',label: 'Fermeture du soir',css_class: 'text-center'}
            edit:
                fields:
                    - { property: 'jour',label: 'jour',css_class: 'text-center'}
                    - { property: 'midiDebut',label: 'Ouverture du midi',css_class: 'text-center'}
                    - { property: 'midifin',label: 'Fermeture du midi',css_class: 'text-center'}
                    - { property: 'soirdebut',label: 'Ouverture du soir',css_class: 'text-center'}
                    - { property: 'soirfin',label: 'Fermeture du soir',css_class: 'text-center'}


        Tva:
            class: App\Entity\Tva
            label: 'Les Tva'
            form:
                title: 'Ajouter une nouvelle TVA'
                fields:
                    - { property: 'multiplicate',label: 'Coéfficiant',css_class: 'text-center'}
                    - { property: 'nom',label: 'nom',css_class: 'text-center'}
                    - { property: 'valeur',label: 'valeur',css_class: 'text-center'}

            list:
                title: "Tva"
                max_results: 10
                fields:
                    - { property: 'multiplicate',label: 'Coéfficiant',css_class: 'text-center'}
                    - { property: 'nom',label: 'nom',css_class: 'text-center'}
                    - { property: 'valeur',label: 'valeur',css_class: 'text-center'}
                    - { property: 'menus',label: 'Nombre de menu',css_class: 'text-center'}
            search:
                fields:
                    - { property: 'multiplicate',label: 'Coéfficiant',css_class: 'text-center'}
                    - { property: 'nom',label: 'nom',css_class: 'text-center'}
                    - { property: 'valeur',label: 'valeur',css_class: 'text-center'}

        Image:
            class: App\Entity\Image
            label: 'Les Images'
            image_base_path: '/images/'
            form:
                title: 'Ajouter une nouvelle TVA'
                fields:
                    - { property: 'path',label: "Chemin de l'image",css_class: 'text-center' }
                    - { property: 'alt',label: "Description de l'image",css_class: 'text-center'}
            list:
                title: "Images"
                max_results: 10
                fields:
                    - { property: 'path',label: "Chemin de l'image",css_class: 'text-center' }
                    - { property: 'path',label: "Image",css_class: 'text-center',type: 'image'}
                    - { property: 'alt',label: "Description de l'image",css_class: 'text-center'}
            search:
                fields:
                    - { property: 'path',label: "Chemin de l'image",css_class: 'text-center'}
                    - { property: 'alt',label: "Description de l'image",css_class: 'text-center'}

    site_name: 'Delice Frites'
    design:
        brand_color: '#343a40'
        color_scheme: 'dark'
        assets:
            favicon:
                path: '/images/Delicefrite/favicoDF.ico'
        menu:
            - label: 'Ventes'
              icon: 'cutlery'
              children:
                - {entity: 'Menus', default: 'true'}
                - Product
                - Category
            - label: 'Information'
              icon: 'info'
              children:
                - Horaire
                - Image
                - Tva
            - {label: 'Sortir', route: 'homePage' ,  icon: 'off'}





#        - App\Entity\Menu
#        - App\Entity\Category
#        - App\Entity\Horaire
#        - App\Entity\Tva
#        - App\Entity\Image